"""Shared training-contract utilities for MotifML."""

from motifml.training.config import (
    TrainingParameterSnapshots,
    build_parameter_snapshots,
    freeze_parameter_snapshot,
)
from motifml.training.contracts import (
    DatasetSplit,
    EvaluationRunMetadata,
    ModelInputMetadata,
    SplitManifestEntry,
    TrainingRunMetadata,
    VocabularyMetadata,
    deserialize_metadata_artifact,
    serialize_metadata_artifact,
)
from motifml.training.token_families import (
    BOS_TOKEN,
    EOS_TOKEN,
    PAD_TOKEN,
    SPECIAL_TOKENS,
    UNK_TOKEN,
    TokenFamily,
    build_control_point_token,
    build_control_span_token,
    build_note_duration_token,
    build_note_pitch_token,
    build_note_string_token,
    build_note_velocity_token,
    build_structure_token,
    build_time_shift_token,
)
from motifml.training.token_ordering import (
    EventTokenSpan,
    expand_sequence_event_spans,
    flatten_token_spans,
)
from motifml.training.versioning import (
    build_contract_version,
    build_feature_version,
    build_model_input_version,
    build_normalized_ir_version,
    build_split_version,
    build_vocabulary_version,
)

__all__ = [
    "BOS_TOKEN",
    "DatasetSplit",
    "EOS_TOKEN",
    "EventTokenSpan",
    "EvaluationRunMetadata",
    "ModelInputMetadata",
    "PAD_TOKEN",
    "SPECIAL_TOKENS",
    "SplitManifestEntry",
    "TrainingRunMetadata",
    "TrainingParameterSnapshots",
    "TokenFamily",
    "UNK_TOKEN",
    "VocabularyMetadata",
    "build_parameter_snapshots",
    "build_contract_version",
    "build_control_point_token",
    "build_control_span_token",
    "build_feature_version",
    "build_model_input_version",
    "build_note_duration_token",
    "build_note_pitch_token",
    "build_note_string_token",
    "build_note_velocity_token",
    "build_normalized_ir_version",
    "build_split_version",
    "build_structure_token",
    "build_time_shift_token",
    "build_vocabulary_version",
    "deserialize_metadata_artifact",
    "expand_sequence_event_spans",
    "flatten_token_spans",
    "freeze_parameter_snapshot",
    "serialize_metadata_artifact",
]
